In [49]:
import re
import pickle
import pandas as pd
import numpy as np
from numpy import nan

In [50]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,average_precision_score,recall_score
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import chi2
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import model_selection, naive_bayes, svm
from sklearn.neighbors import KNeighborsClassifier

from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier
from sklearn.linear_model import SGDClassifier
import matplotlib.pyplot as plt

In [52]:
import pandas as pd
df= pd.read_csv('Dataset_2738_after_webscraping.csv')  

In [53]:


C = (df['Content']).tolist()

L = (df['Label']).tolist()

In [54]:
#PREPROCESSING
def preprocess(col):
    col_l = []
    for r in col:
        #print(r)
        try:
            a = r.lower() 
            a = a.replace("'s", "")
            #a = a.replace(["\n"], "hjfgjh")
            a = re.sub('[^a-zA-Z0-9 \n\.]', '',a)
            a = re.sub('[:.\n\t]', '',a)
            a = re.sub('[?:!.+,]]][]]//;]', '',a) 
            
            col_l.append(a)
        except:
            #print("No header found")
            col_l.append("No Header")
            pass

    # Downloading punkt and wordnet from NLTK
    nltk.download('punkt')
    print("------------------------------------------------------------")
    nltk.download('wordnet')
    
    wordnet_lemmatizer = WordNetLemmatizer()
    
    nltk.download('stopwords')
    
    lemmatized_text_list = []

    for s in col_l:
        #print(s)
        # Create an empty list containing lemmatized words
        lemmatized_list = []

        # Save the text and its words into an object
        #text = df.loc[row]['Content_Parsed_4']
        text_words = s.split(" ")

        # Iterate through every word to lemmatize
        for word in text_words:
            lemmatized_list.append(wordnet_lemmatizer.lemmatize(word, pos="v"))

        # Join the list
        lemmatized_text = " ".join(lemmatized_list)

        # Append to the list containing the texts
        lemmatized_text_list.append(lemmatized_text)
    
    new_lemmatized_text_list = []
    for x in lemmatized_text_list:
        new_lemmatized_text_list.append(" ".join(x.split())) 
    
    pl = pd.Series(new_lemmatized_text_list)
   # pl = pd.Series(col_l)
    stop_words = list(stopwords.words('english'))
    
    for stop_word in stop_words:
        regex_stopword = r"\b" + stop_word + r"\b"
        #pl = pd.Series(col_l)
   
        pl = pl.str.replace(regex_stopword, '')
        
    
    return pl.tolist()

In [55]:
con = preprocess(C)
#print(con)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Jojy\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Jojy\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jojy\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


------------------------------------------------------------


In [56]:
len(con)

2738

In [57]:
L

['iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-project',
 'iot-pr

In [58]:
label = []

In [59]:
for i in L:
    if i == 'iot-project' or i == 'Iot-Project':
        label.append(1)
        
    elif i == 'non-iot-project':
        label.append(0)

In [60]:
len(label)

2738

In [61]:
category_codes = {'non-iot-project': 0, 'iot-project': 1,}

In [62]:
category_codes

{'non-iot-project': 0, 'iot-project': 1}

In [63]:
la2 = pd.Series(label)

In [64]:
la_2 = la2.replace({'Category_Code':category_codes})

In [65]:
la_2

0       1
1       1
2       1
3       1
4       1
       ..
2733    0
2734    0
2735    0
2736    0
2737    0
Length: 2738, dtype: int64

In [66]:
len(la_2)

2738

In [67]:
 df = pd.DataFrame({"Content":con})

In [68]:
df

Content
0     add  follow snippet   html connect  modbus ene...
1     add  follow snippet   html remote control  las...
2     add  follow snippet   html know   go check   t...
3     add  follow snippet   html  simple tutorial  c...
4     add  follow snippet   html tire  joystick cont...
...                                                 ...
2733  321 5 1 feature traditional saffron buns lusse...
2734  7358 55 18 feature  camera bag   useful  carry...
2735  5937 28 13 feature  various reason  wont bore ...
2736  2233 74 6 feature ahoy mateys fancy  cold drin...
2737  2355 44 9 feature one   many fashion trend   l...

[2738 rows x 1 columns]

In [69]:
#####################################  Training Module Starts  #########################################

In [85]:
X_train, X_test, y_train, y_test = train_test_split(df, la_2, test_size=0.15, random_state=8)

In [86]:

X_test

Content
1923  2163 78 1 feature  meat loaf   good choice    ...
1117  add  follow snippet   html   thingsio ai platf...
2154  2742 15 4 feature  make  dress  ive want    cu...
481   add  follow snippet   html use  dark sky api  ...
615   add  follow snippet   html connect multiple da...
...                                                 ...
179   add  follow snippet   html name   box  light  ...
652   add  follow snippet   html transform  energy  ...
2390  230 1 feature make  cardboard carousel  nine l...
2064  936 8 feature im  big guy   want  make  even b...
2683  14426 52 5 feature  test tube vase  exactly   ...

[411 rows x 1 columns]

In [87]:
y_train

392     1
2360    0
1589    0
2492    0
184     1
       ..
2181    0
2409    0
2033    0
1364    1
451     1
Length: 2327, dtype: int64

In [88]:
ngram_range = (1,2)
min_df = 10
max_df = 1.
max_features =300# not clear how to choose this value

In [89]:
tfidf = TfidfVectorizer(encoding='utf-8',
                        ngram_range=ngram_range,
                        stop_words=None,
                        lowercase=False,
                        max_df=max_df,
                        min_df=min_df,
                        max_features=max_features,
                        norm='l2',
                        sublinear_tf=True)

In [90]:
features_train = tfidf.fit_transform(X_train['Content']).toarray()
print(features_train)




[[0.         0.         0.         ... 0.         0.16917262 0.        ]
 [0.         0.         0.05022019 ... 0.         0.         0.        ]
 [0.         0.1856895  0.07417406 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.23613663 0.14122649 0.1423042 ]
 [0.114721   0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [91]:
features_test = tfidf.fit_transform(X_test['Content']).toarray()
print(features_test)


[[0.         0.         0.         ... 0.13206786 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.07204241 0.         ... 0.         0.0783875  0.        ]
 ...
 [0.18709476 0.         0.         ... 0.         0.         0.10855486]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.05115653 0.         0.         ... 0.         0.06094464 0.        ]]


In [92]:


#####################################  Training Module Ends  #########################################

In [93]:
################################## DECISION TREE ###############################################

In [94]:
#DTC =DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,max_features=None, max_leaf_nodes=10, min_samples_leaf=5,min_samples_split=2, min_weight_fraction_leaf=0.0,random_state=None, splitter='random')
DTC = DecisionTreeClassifier(random_state=8)
DTC.fit(features_train, y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=8, splitter='best')

In [95]:
# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(DTC, open(filename, 'wb'))

In [96]:
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(features_test, y_test)
print(result)

0.9951338199513382


In [97]:

DTC_pred = loaded_model.predict(features_test)
DTC_pred

array([0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,

In [98]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_test, DTC_pred)
print(matrix)


[[202   0]
 [  2 207]]


In [99]:
report = classification_report(y_test, DTC_pred)
print(report)

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       202
           1       1.00      0.99      1.00       209

    accuracy                           1.00       411
   macro avg       1.00      1.00      1.00       411
weighted avg       1.00      1.00      1.00       411

